modLoader = "javafml"
loaderVersion = "[1,)"
license = "Apache-2.0"

[[mixins]]
config = "common_events_events.neoforge.mixins.json"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "Common Events Events"
authors = "Kneelawk"
description = "Cross-platform Event Library Events."
logoFile = "assets/${mod_id}/icon.png"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "REQUIRED"
versionRange = "[20.4.148-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "common_events"
type = "REQUIRED"
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "common_events_main_bus"
type = "REQUIRED"
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"
