modLoader = "javafml"
loaderVersion = "[1,)"
license = "Apache-2.0"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "Common Events Kotlin"
authors = "Kneelawk"
description = "Cross-platform Event Library Kotlin adapter."
logoFile = "assets/${mod_id}/icon.png"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "REQUIRED"
versionRange = "[20.6.40-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "common_events"
type = "REQUIRED"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "kotlinforforge"
type = "REQUIRED"
versionRange = "[5,)"
ordering = "NONE"
side = "BOTH"
