modLoader = "javafml"
loaderVersion = "[1,)"
license = "Apache-2.0"

[[mods]]
modId = "common_events_main_bus"
version = "${version}"
displayName = "Common Events Main Bus"
authors = "Kneelawk"
description = "Cross-platform Event Library Main Bus."
logoFile = "assets/common_events_main_bus/icon.png"

[[dependencies.common_events_main_bus]]
modId = "neoforge"
type = "REQUIRED"
versionRange = "[20.4.148-beta,)"
ordering = "NONE"
side = "BOTH"
